"""Build the two fonts unidesk ships, small enough to be cheap in memory.

- Material Symbols Rounded, cut down to the icons listed below (all four
  variation axes survive), plus qml/Icons.js mapping names to characters.
  The full font is ~15 MB.
- Google Sans Flex with only the weight and roundness axes left variable and
  its named instances removed. Qt registers every named instance as its own
  font, which cost ~75 MB of RAM for the original file.

Sources live in tools/fonts-src/ (not committed):
  MaterialSymbolsRounded.ttf + .codepoints  (google/material-design-icons, variablefont/)
  GoogleSansFlex.ttf                         (google/fonts, ofl/googlesansflex/)

    python tools/build_fonts.py
"""
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ROOT = Path(__file__).resolve().parents[1] / "unidesk"
FONTS = ROOT / "fonts"
SOURCE = Path(__file__).parent / "fonts-src" / "MaterialSymbolsRounded.ttf"
CODEPOINTS = Path(__file__).parent / "fonts-src" / "MaterialSymbolsRounded.codepoints"
OUT = FONTS / "MaterialSymbolsRounded-subset.ttf"
JS = ROOT / "qml" / "Icons.js"

ICONS = """
play_arrow pause skip_next skip_previous lyrics music_note graphic_eq
lock settings power_settings_new bedtime restart_alt logout
memory monitor_heart hard_drive thermostat developer_board speed
sunny clear_night partly_cloudy_day partly_cloudy_night cloud foggy rainy weather_snowy thunderstorm
humidity_percentage air visibility wb_twilight water_drop
format_quote star commit call_split book_2 group local_fire_department merge comment
new_releases notifications sell add delete open_with check close arrow_outward
calendar_month schedule expand_more download upload
tune widgets open_in_full remove
wifi lan wifi_off volume_up expand_less search push_pin open_in_new
calculate language folder
content_paste content_copy image notes delete_sweep
swap_vert arrow_downward arrow_upward usb notifications_off clear_all
volume_off volume_down headphones keep sticky_note_2 check_box check_box_outline_blank timer replay stop apps
sports_esports emoji_events trending_up trending_down hourglass_top event photo_library bug_report error
pending cancel task_alt battery_full battery_charging_full bluetooth mouse headset_mic gamepad keyboard
call call_end mic mic_off ring_volume videocam videocam_off screen_share stop_screen_share
chevron_right north_east rocket_launch celebration shuffle edit_note format_list_bulleted coffee
terminal refresh description
""".split()


def main():
    table = {}
    for line in CODEPOINTS.read_text().splitlines():
        name, _, code = line.partition(" ")
        table.setdefault(name, int(code, 16))
    missing = [n for n in ICONS if n not in table]
    if missing:
        raise SystemExit(f"not in Material Symbols: {missing}")

    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    font = TTFont(SOURCE)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[table[n] for n in ICONS])
    subsetter.subset(font)
    font.recalcTimestamp = False  # identical bytes on every build
    font.save(OUT)

    lines = [".pragma library", "// Generated by tools/subset_icons.py", ""]
    reserved = {"delete", "new", "import", "default", "function", "var", "in", "do", "case"}
    lines += [f'var {n + "_" if n in reserved else n} = "\\u{table[n]:04x}";' for n in ICONS]
    JS.parent.mkdir(parents=True, exist_ok=True)
    JS.write_text("\n".join(lines) + "\n")
    print(f"{OUT.name}: {OUT.stat().st_size // 1024} KB, {len(ICONS)} icons")


def build_text_font():
    src = Path(__file__).parent / "fonts-src" / "GoogleSansFlex.ttf"
    out = FONTS / "GoogleSansFlex-unidesk.ttf"
    font = TTFont(src)
    font = instancer.instantiateVariableFont(font, {"opsz": 18, "wdth": 100, "GRAD": 0, "slnt": 0})
    font["fvar"].instances = []
    if "STAT" in font:
        del font["STAT"]
    font.recalcTimestamp = False
    font.save(out)
    print(f"{out.name}: {out.stat().st_size // 1024} KB, axes {[a.axisTag for a in font['fvar'].axes]}")


if __name__ == "__main__":
    main()
    build_text_font()
